#' Gating Method Comparison Framework
#' 
#' A comprehensive framework for testing and comparing automated gating methods
#' across multiple samples in a GatingSet.
#' 
#' @author Generated by Roo
#' @docType package
NULL

# Load required libraries
library(tidyverse)
library(flowCore)
library(flowWorkspace)
library(openCyto)
library(ggcyto)
library(flowDensity)
library(gridExtra)
library(RColorBrewer)
library(rlang)
library(CytoExploreR)

# Source the main package
devtools::load_all()

#' Enhanced channel mapping function
#' 
#' Extends the existing channel mapping to include all channel types
#' 
#' @param gs GatingSet object
#' @return data.frame with Marker, Channel, and Channel_Type columns
create_channel_map_enhanced <- function(gs) {
  gh <- gs[[1]]
  fr <- gh_pop_get_data(gh)
  
  markers <- markernames(fr)
  channels <- names(markers)
  
  # Extract channel types
  channel_types <- ifelse(grepl("-A$", channels), "Area",
                   ifelse(grepl("-H$", channels), "Height",
                   ifelse(grepl("-W$", channels), "Width", "Other")))
  
  # Extract marker names more carefully
  channel_map <- data.frame(
    Marker_Full = markers,
    Channel = channels,
    Channel_Type = channel_types,
    stringsAsFactors = FALSE
  ) %>%
    mutate(
      # Extract just the marker name (before the first colon)
      Marker = trimws(gsub(" :.*", "", Marker_Full))
    )
  
  return(channel_map)
}

#' Wrapper function for gate_mindensity
#' 
#' Applies 1D minimum density gating
#' 
#' @param gs GatingSet object
#' @param parent_pop Parent population path
#' @param target_marker Target marker name
#' @param channel_map Channel mapping data frame
#' @param plot_type Type of plot ("1d" or "2d")
#' @param ssc_channel SSC channel for 2D plots
#' @param ... Additional parameters for gate_mindensity
#' @return List with results and plots
apply_gate_mindensity <- function(gs, parent_pop, target_marker, 
                                  channel_map, plot_type = "1d",
                                  ssc_channel = "SSC-A", ...) {
  # browser()
  # Convert marker to channel
  target_channel <- channel_map$Channel[channel_map$Marker == target_marker & 
                                         channel_map$Channel_Type == "Area"]
  
  if (length(target_channel) == 0) {
    stop("Target marker '", target_marker, "' not found in channel map")
  }
  
  target_channel <- target_channel[1]
  
  results <- list()
  plots <- list()
  
  # Apply to all samples
  for (i in seq_along(gs)) {
    sample_name <- sampleNames(gs)[i]
    gh <- gs[[i]]
    
    # Get parent population data
    parent_data <- gh_pop_get_data(gh, parent_pop)
    
    if (plot_type == "1d") {
      # 1D gating
      gate_result <- tryCatch({
        gate_mindensity(parent_data, channel = target_channel, ...)
      }, error = function(e) {
        warning("gate_mindensity failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 1D histogram plot
      if (!is.null(gate_result)) {
        # Use cyto_plot for 1D histogram
        p <- cyto_plot(parent_data,
                      channels = target_channel,
                      type = "histogram",
                      main = paste("Sample:", sample_name, "- mindensity"))
        # Add vertical line for gate result
        abline(v = gate_result@min, col = "red", lty = "dashed", lwd = 1)
        
        plots[[sample_name]] <- p
      }
    } else if (plot_type == "2d") {
      # 2D gating with SSC-A
      gate_result <- tryCatch({
        gate_mindensity(parent_data, channel = c(target_channel, ssc_channel), ...)
      }, error = function(e) {
        warning("gate_mindensity failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 2D density plot
      if (!is.null(gate_result)) {
        # Extract gate boundaries for plotting
        if (inherits(gate_result, "rectangleGate")) {
          # For rectangle gates, create a data frame with the four corners
          x_min <- gate_result@min[target_channel]
          x_max <- gate_result@max[target_channel]
          y_min <- gate_result@min[ssc_channel]
          y_max <- gate_result@max[ssc_channel]
          
          gate_boundaries <- data.frame(
            x = c(x_min, x_max, x_max, x_min, x_min),
            y = c(y_min, y_min, y_max, y_max, y_min)
          )
        } else {
          # For other gate types, try to use the boundaries slot
          gate_boundaries <- as.data.frame(gate_result@boundaries)
          names(gate_boundaries) <- c(target_channel, ssc_channel)
        }
        
        # Use cyto_plot for 2D density plot
        p <- cyto_plot(parent_data,
                      channels = c(target_channel, ssc_channel),
                      type = "density",
                      main = paste("Sample:", sample_name, "- mindensity (2D)"))
        # Add gate boundary if available
        if (!is.null(gate_boundaries)) {
          lines(gate_boundaries$x, gate_boundaries$y, col = "red", lwd = 2)
        }
        
        plots[[sample_name]] <- p
      }
    }
  }
  
  return(list(results = results, plots = plots))
}

#' Wrapper function for gate_flowclust_1d
#' 
#' Applies 1D flowClust gating
#' 
#' @param gs GatingSet object
#' @param parent_pop Parent population path
#' @param target_marker Target marker name
#' @param channel_map Channel mapping data frame
#' @param plot_type Type of plot ("1d" or "2d")
#' @param ssc_channel SSC channel for 2d plots
#' @param ... Additional parameters for gate_flowclust_1d
#' @return List with results and plots
apply_gate_flowclust_1d <- function(gs, parent_pop, target_marker, 
                                    channel_map, plot_type = "1d",
                                    ssc_channel = "SSC-A", ...) {
  
  # Convert marker to channel
  target_channel <- channel_map$Channel[channel_map$Marker == target_marker & 
                                         channel_map$Channel_Type == "Area"]
  
  if (length(target_channel) == 0) {
    stop("Target marker '", target_marker, "' not found in channel map")
  }
  
  target_channel <- target_channel[1]
  
  results <- list()
  plots <- list()
  
  # Apply to all samples
  for (i in seq_along(gs)) {
    sample_name <- sampleNames(gs)[i]
    gh <- gs[[i]]
    
    # Get parent population data
    parent_data <- gh_pop_get_data(gh, parent_pop)
    # browser()
    if (plot_type == "1d") {
      # 1D gating
      gate_result <- tryCatch({
        gate_flowclust_1d(parent_data, params = target_channel, K=1,...)
      }, error = function(e) {
        warning("gate_flowclust_1d failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 1D histogram plot
      if (!is.null(gate_result)) {
        # Use cyto_plot for 1D histogram
        p <- cyto_plot(parent_data,
                      channels = target_channel,
                      type = "histogram",
                      main = paste("Sample:", sample_name, "- flowclust_1d"))
        # Add vertical line for gate result
        abline(v = gate_result@min, col = "darkgreen", lty = "dashed", lwd = 1)
        
        plots[[sample_name]] <- p
      }
    } else if (plot_type == "2d") {
      # For 2D, we'll still use the 1D gate but plot with SSC-A
      gate_result <- tryCatch({
        gate_flowclust_1d(parent_data, channel = target_channel, K=1, ...)
      }, error = function(e) {
        warning("gate_flowclust_1d failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 2D density plot
      if (!is.null(gate_result)) {
        # Use cyto_plot for 2D density plot
        p <- cyto_plot(parent_data,
                      channels = c(target_channel, ssc_channel),
                      type = "density",
                      main = paste("Sample:", sample_name, "- flowclust_1d (2D)"))
        # Add vertical line for gate result
        abline(v = gate_result@min, col = "darkgreen", lty = "dashed", lwd = 1)
        
        plots[[sample_name]] <- p
      }
    }
  }
  
  return(list(results = results, plots = plots))
}

#' Wrapper function for gate_flowclust_2d
#' 
#' Applies 2D flowClust gating
#' 
#' @param gs GatingSet object
#' @param parent_pop Parent population path
#' @param target_marker Target marker name
#' @param channel_map Channel mapping data frame
#' @param ssc_channel SSC channel for 2D plots
#' @param ... Additional parameters for gate_flowclust_2d
#' @return List with results and plots
apply_gate_flowclust_2d <- function(gs, parent_pop, target_marker, 
                                    channel_map, ssc_channel = "SSC-A", ...) {
  
  # Convert marker to channel
  target_channel <- channel_map$Channel[channel_map$Marker == target_marker & 
                                         channel_map$Channel_Type == "Area"]
  
  if (length(target_channel) == 0) {
    stop("Target marker '", target_marker, "' not found in channel map")
  }
  
  target_channel <- target_channel[1]
  
  results <- list()
  plots <- list()
  
  # Apply to all samples
  for (i in seq_along(gs)) {
    sample_name <- sampleNames(gs)[i]
    gh <- gs[[i]]
    
    # Get parent population data
    parent_data <- gh_pop_get_data(gh, parent_pop)
    
    # 2D gating with target marker and SSC-A
    gate_result <- tryCatch({
      gate_flowclust_2d(parent_data, channels = c(target_channel, ssc_channel), ...)
    }, error = function(e) {
      warning("gate_flowclust_2d failed for sample ", sample_name, ": ", e$message)
      return(NULL)
    })
    
    results[[sample_name]] <- gate_result
    
    # Create 2D density plot
    if (!is.null(gate_result)) {
      # Extract gate boundaries for plotting
      if (inherits(gate_result, "rectangleGate")) {
        # For rectangle gates, create a data frame with the four corners
        x_min <- gate_result@min[target_channel]
        x_max <- gate_result@max[target_channel]
        y_min <- gate_result@min[ssc_channel]
        y_max <- gate_result@max[ssc_channel]
        
        gate_boundaries <- data.frame(
          x = c(x_min, x_max, x_max, x_min, x_min),
          y = c(y_min, y_min, y_max, y_max, y_min)
        )
      } else {
        # For other gate types, try to use the boundaries slot
        gate_boundaries <- as.data.frame(gate_result@boundaries)
        names(gate_boundaries) <- c(target_channel, ssc_channel)
      }
      
      # Extract data properly for flowCore objects
      exprs_data <- exprs(parent_data)
      if (is.matrix(exprs_data) || is.data.frame(exprs_data)) {
        plot_data <- data.frame(x = exprs_data[, target_channel], y = exprs_data[, ssc_channel])
      } else {
        plot_data <- data.frame(x = exprs_data[[target_channel]], y = exprs_data[[ssc_channel]])
      }
      names(plot_data) <- c(target_channel, ssc_channel)
      p <- ggplot(plot_data, aes(x = .data[[target_channel]], y = .data[[ssc_channel]])) +
        geom_density_2d() +
        geom_polygon(data = gate_boundaries,
                     aes(x = .data[["x"]], y = .data[["y"]]),
                     fill = "blue", alpha = 0.3) +
        labs(title = paste("Sample:", sample_name, "- flowclust_2d"),
             x = target_marker, y = "SSC-A") +
        theme_minimal()
      
      plots[[sample_name]] <- p
    }
  }
  
  return(list(results = results, plots = plots))
}

#' Wrapper function for gate_tailgate
#' 
#' Applies tailgating for rare population detection
#' 
#' @param gs GatingSet object
#' @param parent_pop Parent population path
#' @param target_marker Target marker name
#' @param channel_map Channel mapping data frame
#' @param plot_type Type of plot ("1d" or "2d")
#' @param ssc_channel SSC channel for 2d plots
#' @param ... Additional parameters for gate_tailgate
#' @return List with results and plots
apply_gate_tailgate <- function(gs, parent_pop, target_marker, 
                                 channel_map, plot_type = "1d",
                                 ssc_channel = "SSC-A", ...) {
  
  # Convert marker to channel
  target_channel <- channel_map$Channel[channel_map$Marker == target_marker & 
                                         channel_map$Channel_Type == "Area"]
  
  if (length(target_channel) == 0) {
    stop("Target marker '", target_marker, "' not found in channel map")
  }
  
  target_channel <- target_channel[1]
  
  results <- list()
  plots <- list()
  
  # Apply to all samples
  for (i in seq_along(gs)) {
    sample_name <- sampleNames(gs)[i]
    gh <- gs[[i]]
    
    # Get parent population data
    parent_data <- gh_pop_get_data(gh, parent_pop)
    
    if (plot_type == "1d") {
      # 1D gating
      gate_result <- tryCatch({
        gate_tailgate(parent_data, channel = target_channel, ...)
      }, error = function(e) {
        warning("gate_tailgate failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 1D histogram plot
      if (!is.null(gate_result)) {
        # Extract data properly for flowCore objects
        exprs_data <- exprs(parent_data)
        if (is.matrix(exprs_data) || is.data.frame(exprs_data)) {
          plot_data <- data.frame(x = exprs_data[, target_channel])
        } else {
          plot_data <- data.frame(x = exprs_data[[target_channel]])
        }
        names(plot_data) <- target_channel
        p <- ggplot(plot_data, aes(x = .data[[target_channel]])) +
          geom_histogram(bins = 100, alpha = 0.7, fill = "lightcoral", color = "black") +
          geom_vline(xintercept = gate_result@min,
                     color = "darkred", linetype = "dashed", size = 1) +
          labs(title = paste("Sample:", sample_name, "- tailgate"),
               x = target_marker, y = "Cell Count") +
          theme_minimal()
        
        plots[[sample_name]] <- p
      }
    } else if (plot_type == "2d") {
      # For 2D, we'll still use the 1D gate but plot with SSC-A
      gate_result <- tryCatch({
        gate_tailgate(parent_data, channel = target_channel, ...)
      }, error = function(e) {
        warning("gate_tailgate failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 2D density plot
      if (!is.null(gate_result)) {
        # Extract data properly for flowCore objects
        exprs_data <- exprs(parent_data)
        if (is.matrix(exprs_data) || is.data.frame(exprs_data)) {
          plot_data <- data.frame(x = exprs_data[, target_channel], y = exprs_data[, ssc_channel])
        } else {
          plot_data <- data.frame(x = exprs_data[[target_channel]], y = exprs_data[[ssc_channel]])
        }
        names(plot_data) <- c(target_channel, ssc_channel)
        p <- ggplot(plot_data, aes(x = .data[[target_channel]], y = .data[[ssc_channel]])) +
          geom_density_2d() +
          geom_vline(xintercept = gate_result@min,
                     color = "darkred", linetype = "dashed", size = 1) +
          labs(title = paste("Sample:", sample_name, "- tailgate (2D)"),
               x = target_marker, y = "SSC-A") +
          theme_minimal()
        
        plots[[sample_name]] <- p
      }
    }
  }
  
  return(list(results = results, plots = plots))
}

#' Wrapper function for gate_quantile
#' 
#' Applies quantile-based gating
#' 
#' @param gs GatingSet object
#' @param parent_pop Parent population path
#' @param target_marker Target marker name
#' @param channel_map Channel mapping data frame
#' @param plot_type Type of plot ("1d" or "2d")
#' @param ssc_channel SSC channel for 2d plots
#' @param ... Additional parameters for gate_quantile
#' @return List with results and plots
apply_gate_quantile <- function(gs, parent_pop, target_marker, 
                                 channel_map, plot_type = "1d",
                                 ssc_channel = "SSC-A", ...) {
  
  # Convert marker to channel
  target_channel <- channel_map$Channel[channel_map$Marker == target_marker & 
                                         channel_map$Channel_Type == "Area"]
  
  if (length(target_channel) == 0) {
    stop("Target marker '", target_marker, "' not found in channel map")
  }
  
  target_channel <- target_channel[1]
  
  results <- list()
  plots <- list()
  
  # Apply to all samples
  for (i in seq_along(gs)) {
    sample_name <- sampleNames(gs)[i]
    gh <- gs[[i]]
    
    # Get parent population data
    parent_data <- gh_pop_get_data(gh, parent_pop)
    
    if (plot_type == "1d") {
      # 1D gating
      gate_result <- tryCatch({
        gate_quantile(parent_data, channel = target_channel, ...)
      }, error = function(e) {
        warning("gate_quantile failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 1D histogram plot
      if (!is.null(gate_result)) {
        # Extract data properly for flowCore objects
        exprs_data <- exprs(parent_data)
        if (is.matrix(exprs_data) || is.data.frame(exprs_data)) {
          plot_data <- data.frame(x = exprs_data[, target_channel])
        } else {
          plot_data <- data.frame(x = exprs_data[[target_channel]])
        }
        names(plot_data) <- target_channel
        p <- ggplot(plot_data, aes(x = .data[[target_channel]])) +
          geom_histogram(bins = 100, alpha = 0.7, fill = "lightyellow", color = "black") +
          geom_vline(xintercept = gate_result@min,
                     color = "orange", linetype = "dashed", size = 1) +
          labs(title = paste("Sample:", sample_name, "- quantile"),
               x = target_marker, y = "Cell Count") +
          theme_minimal()
        
        plots[[sample_name]] <- p
      }
    } else if (plot_type == "2d") {
      # For 2D, we'll still use the 1D gate but plot with SSC-A
      gate_result <- tryCatch({
        gate_quantile(parent_data, channel = target_channel, ...)
      }, error = function(e) {
        warning("gate_quantile failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 2D density plot
      if (!is.null(gate_result)) {
        # Extract data properly for flowCore objects
        exprs_data <- exprs(parent_data)
        if (is.matrix(exprs_data) || is.data.frame(exprs_data)) {
          plot_data <- data.frame(x = exprs_data[, target_channel], y = exprs_data[, ssc_channel])
        } else {
          plot_data <- data.frame(x = exprs_data[[target_channel]], y = exprs_data[[ssc_channel]])
        }
        names(plot_data) <- c(target_channel, ssc_channel)
        p <- ggplot(plot_data, aes(x = .data[[target_channel]], y = .data[[ssc_channel]])) +
          geom_density_2d() +
          geom_vline(xintercept = gate_result@min,
                     color = "orange", linetype = "dashed", size = 1) +
          labs(title = paste("Sample:", sample_name, "- quantile (2D)"),
               x = target_marker, y = "SSC-A") +
          theme_minimal()
        
        plots[[sample_name]] <- p
      }
    }
  }
  
  return(list(results = results, plots = plots))
}

#' Wrapper function for deGate from flowDensity
#' 
#' Applies deGate algorithm for automated gating
#' 
#' @param gs GatingSet object
#' @param parent_pop Parent population path
#' @param target_marker Target marker name
#' @param channel_map Channel mapping data frame
#' @param plot_type Type of plot ("1d" or "2d")
#' @param ssc_channel SSC channel for 2d plots
#' @param ... Additional parameters for deGate
#' @return List with results and plots
apply_deGate <- function(gs, parent_pop, target_marker, 
                         channel_map, plot_type = "1d",
                         ssc_channel = "SSC-A", ...) {
  
  # Convert marker to channel
  target_channel <- channel_map$Channel[channel_map$Marker == target_marker & 
                                         channel_map$Channel_Type == "Area"]
  
  if (length(target_channel) == 0) {
    stop("Target marker '", target_marker, "' not found in channel map")
  }
  
  target_channel <- target_channel[1]
  
  results <- list()
  plots <- list()
  
  # Apply to all samples
  for (i in seq_along(gs)) {
    sample_name <- sampleNames(gs)[i]
    gh <- gs[[i]]
    
    # Get parent population data
    parent_data <- gh_pop_get_data(gh, parent_pop)
    
    if (plot_type == "1d") {
      # 1D gating
      # Try to use deGate from flowDensity if available, otherwise skip
      gate_result <- tryCatch({
        if (requireNamespace("flowDensity", quietly = TRUE)) {
          flowDensity::deGate(parent_data, channel = target_channel, ...)
        } else {
          stop("flowDensity package not available")
        }
      }, error = function(e) {
        warning("deGate failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 1D histogram plot
      if (!is.null(gate_result)) {
        # Extract data properly for flowCore objects
        exprs_data <- exprs(parent_data)
        if (is.matrix(exprs_data) || is.data.frame(exprs_data)) {
          plot_data <- data.frame(x = exprs_data[, target_channel])
        } else {
          plot_data <- data.frame(x = exprs_data[[target_channel]])
        }
        names(plot_data) <- target_channel
        p <- ggplot(plot_data, aes(x = .data[[target_channel]])) +
          geom_histogram(bins = 100, alpha = 0.7, fill = "lightpink", color = "black") +
          # deGate returns a numeric value for 1D gating
          # deGate returns a numeric value for 1D gating
          geom_vline(xintercept = gate_result,
                     color = "purple", linetype = "dashed", size = 1) +
          labs(title = paste("Sample:", sample_name, "- deGate"),
               x = target_marker, y = "Cell Count") +
          theme_minimal()
        
        plots[[sample_name]] <- p
      }
    } else if (plot_type == "2d") {
      # For 2D, we'll still use the 1D gate but plot with SSC-A
      # Try to use deGate from flowDensity if available, otherwise skip
      gate_result <- tryCatch({
        if (requireNamespace("flowDensity", quietly = TRUE)) {
          flowDensity::deGate(parent_data, channel = target_channel, ...)
        } else {
          stop("flowDensity package not available")
        }
      }, error = function(e) {
        warning("deGate failed for sample ", sample_name, ": ", e$message)
        return(NULL)
      })
      
      results[[sample_name]] <- gate_result
      
      # Create 2D density plot
      if (!is.null(gate_result)) {
        # Extract data properly for flowCore objects
        exprs_data <- exprs(parent_data)
        if (is.matrix(exprs_data) || is.data.frame(exprs_data)) {
          plot_data <- data.frame(x = exprs_data[, target_channel], y = exprs_data[, ssc_channel])
        } else {
          plot_data <- data.frame(x = exprs_data[[target_channel]], y = exprs_data[[ssc_channel]])
        }
        names(plot_data) <- c(target_channel, ssc_channel)
        p <- ggplot(plot_data, aes(x = .data[[target_channel]], y = .data[[ssc_channel]])) +
          geom_density_2d() +
          geom_vline(xintercept = gate_result, 
                     color = "purple", linetype = "dashed", size = 1) +
          labs(title = paste("Sample:", sample_name, "- deGate (2D)"),
               x = target_marker, y = "SSC-A") +
          theme_minimal()
        
        plots[[sample_name]] <- p
      }
    }
  }
  
  return(list(results = results, plots = plots))
}

#' Create comparison grid of all gating methods
#' 
#' @param method_plots List of plots from different gating methods
#' @param output_file File path to save the grid plot
#' @return Grid plot object
create_comparison_grid <- function(method_plots, output_file = NULL) {
  # Combine all plots into a grid
  # This assumes method_plots is a list with named elements for each method
  # and each element contains plots for different samples
  
  # For simplicity, we'll create a grid for the first sample
  sample_name <- names(method_plots[[1]])[1]
  
  plots_list <- lapply(method_plots, function(x) x[[sample_name]])
  
  # Remove any NULL plots
  plots_list <- plots_list[!sapply(plots_list, is.null)]
  
  # Create grid
  grid_plot <- do.call(grid.arrange, c(plots_list, ncol = 2))
  
  if (!is.null(output_file)) {
    ggsave(output_file, grid_plot, width = 12, height = 8)
  }
  
  return(grid_plot)
}

#' Generate statistical summary for gating results
#' 
#' @param gs GatingSet object
#' @param parent_pop Parent population path
#' @param method_results List of results from different gating methods
#' @return Data frame with summary statistics
generate_summary_stats <- function(gs, parent_pop, method_results) {
  summary_df <- data.frame(
    Sample = character(),
    Method = character(),
    Parent_Count = numeric(),
    Gated_Count = numeric(),
    Percentage = numeric(),
    stringsAsFactors = FALSE
  )
  
  sample_names <- sampleNames(gs)
  
  for (method_name in names(method_results)) {
    method_res <- method_results[[method_name]]
    
    for (sample_name in sample_names) {
      # Get parent population count
      parent_count <- gh_pop_get_count(gs[[which(sample_names == sample_name)]], parent_pop)
      
      # Get gated count (this would depend on how the gate is applied to the GatingSet)
      # For now, we'll just put placeholder values
      gated_count <- NA
      percentage <- NA
      
      # Add to summary
      summary_df <- rbind(summary_df, data.frame(
        Sample = sample_name,
        Method = method_name,
        Parent_Count = parent_count,
        Gated_Count = gated_count,
        Percentage = percentage,
        stringsAsFactors = FALSE
      ))
    }
  }
  
  return(summary_df)
}

#' Main function to compare gating methods
#' 
#' @param gs GatingSet object
#' @param parent_pop Parent population path
#' @param target_marker Target marker name
#' @param methods Vector of method names to compare
#' @param plot_types Vector of plot types ("1d", "2d")
#' @param output_dir Directory to save results
#' @param ... Additional parameters passed to gating methods
#' @return List with results, plots, and summary
compare_gating_methods <- function(gs, parent_pop, target_marker, 
                                    methods = c("mindensity", "flowclust_1d", "flowclust_2d", 
                                               "tailgate", "quantile", "deGate"),
                                    plot_types = c("1d", "2d"),
                                    output_dir = "results/gating_comparison",
                                    ...) {
  
  # Create output directory
  dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
  dir.create(file.path(output_dir, "plots"), showWarnings = FALSE, recursive = TRUE)
  dir.create(file.path(output_dir, "data"), showWarnings = FALSE, recursive = TRUE)
  
  # Create enhanced channel map
  channel_map <- create_channel_map_enhanced(gs)
  
  # Store results and plots
  all_results <- list()
  all_plots <- list()
  
  # Apply each method
  for (method in methods) {
    cat("Applying", method, "...\n")
    
    # Determine which function to call
    gating_func <- switch(method,
      "mindensity" = apply_gate_mindensity,
      "flowclust_1d" = apply_gate_flowclust_1d,
      "flowclust_2d" = apply_gate_flowclust_2d,
      "tailgate" = apply_gate_tailgate,
      "quantile" = apply_gate_quantile,
      "deGate" = apply_deGate,
      stop("Unknown method: ", method)
    )
    
    # Apply for each plot type
    method_results <- list()
    method_plots <- list()
    
    for (plot_type in plot_types) {
      # Call the appropriate function
      if (method %in% c("mindensity", "flowclust_1d", "tailgate", "quantile", "deGate")) {
        res <- gating_func(gs, parent_pop, target_marker, channel_map, 
                           plot_type = plot_type, ...)
        method_results[[plot_type]] <- res$results
        method_plots[[plot_type]] <- res$plots
      } else if (method == "flowclust_2d") {
        # flowclust_2d is always 2D
        if (plot_type == "2d") {
          res <- gating_func(gs, parent_pop, target_marker, channel_map, ...)
          method_results[[plot_type]] <- res$results
          method_plots[[plot_type]] <- res$plots
        }
      }
    }
    
    all_results[[method]] <- method_results
    all_plots[[method]] <- method_plots
  }
  
  # Generate summary statistics
  summary_stats <- generate_summary_stats(gs, parent_pop, all_results)
  
  # Create comparison grids
  comparison_grids <- list()
  for (plot_type in plot_types) {
    # Collect plots for this plot type
    plots_for_type <- list()
    for (method in methods) {
      if (!is.null(all_plots[[method]][[plot_type]])) {
        plots_for_type[[method]] <- all_plots[[method]][[plot_type]]
      }
    }
    
    if (length(plots_for_type) > 0) {
      grid_file <- file.path(output_dir, "plots", 
                            paste0("comparison_grid_", plot_type, ".png"))
      comparison_grids[[plot_type]] <- create_comparison_grid(plots_for_type, grid_file)
    }
  }
  
  # Save results
  saveRDS(list(
    results = all_results,
    plots = all_plots,
    summary = summary_stats,
    grids = comparison_grids
  ), file.path(output_dir, "data", "gating_comparison_results.rds"))
  
  # Save summary statistics
  write.csv(summary_stats, file.path(output_dir, "data", "summary_statistics.csv"), 
            row.names = FALSE)
  
  # Return results
  return(list(
    results = all_results,
    plots = all_plots,
    summary = summary_stats,
    grids = comparison_grids,
    output_dir = output_dir
  ))
}

