#' Test script for gating method comparison framework
#' 
#' This script demonstrates how to use the gating comparison framework
#' with the existing GatingSet from gating_set_manipulation.R
#' 
#' @author Generated by Roo
#' @docType script

# Load required libraries
library(tidyverse)
library(flowCore)
library(flowWorkspace)
library(openCyto)
library(ggcyto)

# Source the main package and framework
devtools::load_all()
source("export_approaches/gating_comparison_framework.R")

# Environment detection pattern (use this in all scripts)
base_path <- {
  mac_paths <- Sys.glob("/Volumes/scBiomarkers*/bernd")
  if (length(mac_paths) > 0) {
    dirname(mac_paths[1])  # Remove /bernd and use first match
  } else {
    "/pasteur/helix/projects/scBiomarkers/bernd"  # Server environment
  }
}

base_data_path <- {
  mac_paths <- Sys.glob("/Volumes/bernd*/cytometry")
  if (length(mac_paths) > 0) {
    mac_paths[1]  # Use the full path directly
  } else {
    setwd("/pasteur/helix/projects/scBiomarkers/bernd/cytometry/CyFj11/")
    "/pasteur/helix/projects/LabExMI/USERS/bernd/cytometry"  # Server environment
  }
}

# Load the existing GatingSet
# Try to load from saved file first
if (file.exists("gs_dev.rds")) {
  gs <- readRDS("gs_dev.rds")
  cat("Loaded GatingSet from gs_dev.rds\n")
} else {
  # If not available, recreate it
  cat("Recreating GatingSet from workspace...\n")
  
  # Parse the workspace file
  ws <- read_flowjo11_workspace("inst/mi.3samples.2gates.flowjo")
  
  # Process the gating set with the correct group
  gs <- fj11_to_gatingset(fj11_workspace = ws,
                          group_name = "Experiment Data",  # Use the correct group name
                          stop_on_multiple=FALSE,
                          keywords = c("File Name", "File URI", "Compensation Matrix"),
                          path = file.path(base_data_path, "analysis/MIV3.01.30.26/FCS_files/")
  )
  
  # Save for future use
  saveRDS(gs, "gs_dev.rds")
  cat("Saved GatingSet to gs_dev.rds\n")
}

# Check that we have a valid GatingSet
if (is.null(gs)) {
  stop("Failed to load or create GatingSet")
}

# Display basic information about the GatingSet
cat("GatingSet information:\n")
cat("Number of samples:", length(gs), "\n")
cat("Sample names:", paste(sampleNames(gs), collapse = ", "), "\n")

# Get population paths
all_pops <- flowWorkspace::gs_get_pop_paths(gs)
cat("Available populations:\n")
print(head(all_pops, 10))

# Create enhanced channel map
channel_map <- create_channel_map_enhanced(gs)
cat("Channel mapping:\n")
print(head(channel_map, 10))

# Define test parameters
parent_pop <- "root"  # Start with root population
target_marker <- "CD45RA"  # Example marker

# Check if target marker exists in channel map
if (!(target_marker %in% channel_map$Marker)) {
  cat("Target marker", target_marker, "not found in channel map.\n")
  cat("Available markers:\n")
  print(unique(channel_map$Marker))
  
  # Use the first available marker for testing
  target_marker <- unique(channel_map$Marker)[1]
  cat("Using", target_marker, "as target marker for testing.\n")
}

# Test the comparison framework
cat("Running gating method comparison...\n")

# For demonstration, we'll run a limited comparison with simplified parameters
results <- compare_gating_methods(
  gs = gs,
  parent_pop = parent_pop,
  target_marker = target_marker,
  methods = c("mindensity", "flowclust_1d", "quantile"),  # Subset for demo
  plot_types = c("1d"),  # Just 1D for demo
  output_dir = "results/gating_comparison_demo",
  # Simplified parameters for demonstration
  tol = 0.01,  # For methods that support it
  quantile = 0.8  # For methods that support it
)

# Display results summary
cat("Comparison completed. Results saved to:", results$output_dir, "\n")
cat("Summary statistics:\n")
print(head(results$summary))

# Show where plots were saved
plots_dir <- file.path(results$output_dir, "plots")
if (dir.exists(plots_dir)) {
  cat("Plot files created:\n")
  plot_files <- list.files(plots_dir, full.names = TRUE)
  print(plot_files)
}

# Show where data was saved
data_dir <- file.path(results$output_dir, "data")
if (dir.exists(data_dir)) {
  cat("Data files created:\n")
  data_files <- list.files(data_dir, full.names = TRUE)
  print(data_files)
}

# Example of how to access individual plots
cat("Example of accessing individual plots:\n")
for (method in names(results$plots)) {
  if (!is.null(results$plots[[method]]$`1d`)) {
    sample_names <- names(results$plots[[method]]$`1d`)
    if (length(sample_names) > 0) {
      first_sample <- sample_names[1]
      cat("- ", method, "plot for", first_sample, "is available\n")
    }
  }
}

# Example of how to display a plot (uncomment to actually display)
# if (length(results$grids) > 0) {
#   print(results$grids[[1]])
# }

cat("Test completed successfully!\n")
